version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.16-browsers

    environment:
      OUTPUT_DIR: /tmp/output/tintin
    resource_class: xlarge # 8 vCPUs, 16 GB RAM
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install deps
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
            -
      - run:
          name: Lint
          command: |
            yarn lint

      - run:
          name: Jest unit tests
          command: |
            yarn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
